# This defines the deployment that runs the frontend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # namespace: local-cluster ## Uncomment if you want to deploy in a specific namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never
---
# This defines the service that exposes the frontend application
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # namespace: local-cluster ## Uncomment if you want to deploy in a specific namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080