# This defines the deployment that runs the frontend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: small-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: alecoeto/small-page:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
# This defines the service that exposes the frontend application
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: small-page
spec:
  type: LoadBalancer 
  loadBalancerIP: 20.118.70.76
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
